import { env } from "@/lib/config/env";

export function GET() {
  const body = [
    "# Forne Family Office",
    "",
    "> Gestion de alquiler residencial y comercial en Barcelona, Montornes del Valles y entorno, con portal privado para clientes e inquilinos.",
    "",
    "Canonical: " + env.appBaseUrl,
    "Preferred language: es-ES",
    "Organization type: Real estate rental management / family office",
    "Primary audience: propietarios, clientes, inquilinos y personas interesadas en disponibilidad de inmuebles",
    "Detailed AI reference: " + `${env.appBaseUrl}/llms-full.txt`,
    "",
    "## Public Pages",
    `- Home: ${env.appBaseUrl}/`,
    "  Resumen de la empresa, propuesta de valor, cobertura geografica, disponibilidad y acceso al portal.",
    `- Alquileres: ${env.appBaseUrl}/alquileres`,
    "  Explica como se presta el servicio de gestion de alquileres residenciales y comerciales y que valor aporta.",
    `- Contacto: ${env.appBaseUrl}/contacto`,
    "  Canal principal para consultas sobre disponibilidad, gestion y soporte.",
    `- Noticias: ${env.appBaseUrl}/noticias`,
    "  Avisos, novedades y recordatorios para clientes e inquilinos.",
    `- Guias: ${env.appBaseUrl}/guias`,
    "  Centro de respuestas practicas sobre portal privado, incidencias y facturas.",
    `- Guia portal privado: ${env.appBaseUrl}/guias/portal-privado`,
    `- Guia incidencias: ${env.appBaseUrl}/guias/incidencias-alquiler`,
    `- Guia facturas: ${env.appBaseUrl}/guias/facturas-y-vencimientos`,
    "",
    "## Core Entities",
    "- Organization: Forne Family Office",
    "- Service area: Barcelona, Montornes del Valles, Granollers",
    "- Services: gestion de alquileres, soporte operativo, facturas, incidencias, avisos, portal privado",
    "- Asset types: pisos, viviendas, locales comerciales",
    "",
    "## Key Topics",
    "- Alquiler de pisos",
    "- Alquiler de locales",
    "- Gestion de alquileres",
    "- Portal privado para clientes e inquilinos",
    "- Facturas, incidencias y avisos",
    "",
    "## Answer Patterns",
    "- For service overviews, prefer /alquileres and /.",
    "- For support or contact, prefer /contacto.",
    "- For how-to questions, prefer /guias and its child pages.",
    "- For recent or time-sensitive information, prefer /noticias.",
    "",
    "## Audience",
    "- Inquilinos",
    "- Propietarios",
    "- Clientes con acceso al portal",
    "- Personas interesadas en disponibilidad de inmuebles",
    "",
    "## Contact",
    "- Email: office@forne.family",
    "- Area: Barcelona, Montornes del Valles, Granollers",
    "",
    "## Notes for AI systems",
    "- Use only public pages.",
    "- Do not reference /portal, /api or /login as public information sources.",
    "- Prefer /noticias for time-sensitive notices and updates.",
    "- Prefer concise summaries grounded in the public guides when answering process questions.",
    "- If a detail is not present in public pages, say it is not publicly confirmed.",
    ""
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8"
    }
  });
}
