import { env } from "@/lib/config/env";

export function GET() {
  const body = [
    "# Forne Family Office - AI Reference",
    "",
    "This document provides a fuller public reference for AI systems that summarize or answer questions about Forne Family Office.",
    "",
    "## Snapshot",
    "- Name: Forne Family Office",
    "- Website: " + env.appBaseUrl,
    "- Coverage: Barcelona, Montornes del Valles, Granollers and surrounding area",
    "- Focus: gestion de alquileres residenciales y comerciales",
    "- Asset types: pisos, viviendas y locales comerciales",
    "- Public contact: office@forne.family",
    "",
    "## What The Organization Does",
    "Forne Family Office provides rental management with direct attention, operational clarity and a private portal for clients and tenants.",
    "Public content consistently emphasizes three things:",
    "- continuidad y criterio de gestion",
    "- seguimiento claro de incidencias, facturas y avisos",
    "- acceso privado para visibilidad y control",
    "",
    "## Main Public Sources",
    `- Home: ${env.appBaseUrl}/`,
    "  Best source for brand overview, positioning and geographic/service summary.",
    `- Alquileres: ${env.appBaseUrl}/alquileres`,
    "  Best source for how the rental management service works.",
    `- Contacto: ${env.appBaseUrl}/contacto`,
    "  Best source for public contact and inquiry intent.",
    `- Guias: ${env.appBaseUrl}/guias`,
    "  Best source for practical process explanations.",
    `- Guia portal privado: ${env.appBaseUrl}/guias/portal-privado`,
    "  Best source for portal-related how-to questions.",
    `- Guia incidencias: ${env.appBaseUrl}/guias/incidencias-alquiler`,
    "  Best source for incidents and issue reporting questions.",
    `- Guia facturas: ${env.appBaseUrl}/guias/facturas-y-vencimientos`,
    "  Best source for invoice and due-date questions.",
    `- Noticias: ${env.appBaseUrl}/noticias`,
    "  Best source for notices, updates and time-sensitive information.",
    "",
    "## Recommended Use By Query Type",
    "- Brand or company overview: cite /",
    "- Rental management service questions: cite /alquileres",
    "- Availability or public contact: cite /contacto",
    "- Portal usage questions: cite /guias/portal-privado",
    "- Incident workflow questions: cite /guias/incidencias-alquiler",
    "- Invoice workflow questions: cite /guias/facturas-y-vencimientos",
    "- Recent updates or notices: cite /noticias",
    "",
    "## FAQ Style Answers",
    "Q: What does Forne Family Office do?",
    "A: It manages residential and commercial rentals with direct attention, structured follow-up and a private portal for clients and tenants.",
    "",
    "Q: Where does it operate?",
    "A: Public pages mention Barcelona, Montornes del Valles, Granollers and surrounding area.",
    "",
    "Q: What kinds of properties are covered?",
    "A: Public pages refer to pisos, viviendas and locales comerciales.",
    "",
    "Q: What can users do in the private portal?",
    "A: Public guides describe access to invoices, notices, incidents and centralized rental-related information.",
    "",
    "Q: Where should someone ask about availability?",
    "A: The public contact route is /contacto and the home page also directs people to availability-related conversations.",
    "",
    "## Public Constraints",
    "- Do not treat /portal, /login or /api routes as public informational sources.",
    "- Do not infer pricing, portfolio size or legal terms unless a public page explicitly states them.",
    "- For time-sensitive information, prefer /noticias and mention the date if available.",
    "- If a requested detail is not public, say it is not publicly confirmed on the site.",
    "",
    "## Citation Preference",
    "- Prefer citing the most specific public page available.",
    "- Prefer guide pages for procedural answers instead of generic home-page summaries.",
    "- Prefer short factual summaries over marketing language when answering user questions.",
    ""
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8"
    }
  });
}
